---
- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}" 
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'nginx', state: 'present' }

# - name: loops demo
#   hosts: web
#   become: yes
#   tasks:
#   - name: install packages
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: present 
#     loop:
#     - mysql
#     - nginx
#     - postfix
#     - httpd


# - name: loops demo
#   hosts: local
#   connection: local
#   tasks:
#   - name: print names
#     ansible.builtin.debug:
#       msg: "Hello {{ item }}"
#     loop:
#     - Ramesh
#     - Suresh
#     - Robert
#     - Raheem





# - name: Install packages
#   apt:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - git
#     - curl
#     - vim

# - name: Configure users
#   user:
#     name: "{{ item.name }}"
#     state: present
#     groups: "{{ item.groups }}"
#   loop:
#     - { name: 'user1', groups: 'sudo' }
#     - { name: 'user2', groups: 'admin' }
